'use client'

import { useState, useEffect } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Plus, Edit, Trash2, CheckCircle, Calendar, Settings, BookOpen, Zap, BarChart3 } from 'lucide-react'
import { TahunAkademikDialog } from '@/components/admin/tahun-akademik/TahunAkademikDialog'
import { AutoGenerateDialog } from '@/components/admin/tahun-akademik/AutoGenerateDialog'
import { TahunAkademikSelector } from '@/components/admin/tahun-akademik/TahunAkademikSelector'
import LayoutApp from '@/components/layout/LayoutApp'
import { useToast } from '@/hooks/use-toast'
import { format } from 'date-fns'
import { id } from 'date-fns/locale'

interface TahunAkademik {
  id: number
  tahunMulai: number
  tahunSelesai: number
  semester: 'S1' | 'S2'
  namaLengkap: string
  tanggalMulai: string
  tanggalSelesai: string
  isActive: boolean
  createdAt: string
  updatedAt: string
  creator?: {
    namaLengkap: string
  }
  _count?: {
    templateUjian: number
    templateRaport: number
    ujianSantri: number
    raportSantri: number
  }
}

export default function TahunAkademikPage() {
  const [tahunAkademik, setTahunAkademik] = useState<TahunAkademik[]>([])
  const [loading, setLoading] = useState(true)
  const [selectedTahun, setSelectedTahun] = useState<TahunAkademik | null>(null)
  const [showDialog, setShowDialog] = useState(false)
  const [showAutoGenerate, setShowAutoGenerate] = useState(false)
  const [activeTahunAkademik, setActiveTahunAkademik] = useState<TahunAkademik | null>(null)
  const { toast } = useToast()

  useEffect(() => {
    fetchTahunAkademik()
  }, [])

  const fetchTahunAkademik = async () => {
    try {
      const response = await fetch('/api/admin/tahun-akademik')
      if (response.ok) {
        const result = await response.json()
        if (result.success) {
          setTahunAkademik(result.data)
        }
      }
    } catch (error) {
      toast({
        title: "Error",
        description: "Gagal memuat data tahun akademik",
        variant: "destructive"
      })
    } finally {
      setLoading(false)
    }
  }

  const handleDelete = async (id: number) => {
    if (!confirm('Yakin ingin menghapus tahun akademik ini?')) return

    try {
      const response = await fetch(`/api/admin/tahun-akademik/${id}`, {
        method: 'DELETE'
      })

      if (response.ok) {
        toast({
          title: "Berhasil",
          description: "Tahun akademik berhasil dihapus"
        })
        fetchTahunAkademik()
      } else {
        const error = await response.json()
        throw new Error(error.message || 'Gagal menghapus tahun akademik')
      }
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || "Gagal menghapus tahun akademik",
        variant: "destructive"
      })
    }
  }

  const handleSetActive = async (id: number) => {
    try {
      const response = await fetch('/api/admin/tahun-akademik/active', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ tahunAjaranId: id })
      })

      const result = await response.json()

      if (result.success) {
        toast({
          title: "Berhasil",
          description: result.message
        })
        fetchTahunAkademik()
      } else {
        throw new Error(result.error || 'Gagal mengaktifkan tahun akademik')
      }
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || "Gagal mengaktifkan tahun akademik",
        variant: "destructive"
      })
    }
  }

  const getSemesterIcon = (semester: string) => {
    return semester === 'S1' ? '🌞' : '❄️'
  }

  const getSemesterLabel = (semester: string) => {
    return semester === 'S1' ? 'Semester 1' : 'Semester 2'
  }

  const formatDateRange = (mulai: string, selesai: string) => {
    const startDate = new Date(mulai).toLocaleDateString('id-ID', { 
      day: 'numeric', 
      month: 'short' 
    })
    const endDate = new Date(selesai).toLocaleDateString('id-ID', { 
      day: 'numeric', 
      month: 'short', 
      year: 'numeric' 
    })
    return `${startDate} - ${endDate}`
  }

  const handleAutoGenerateSuccess = () => {
    fetchTahunAkademik()
    setShowAutoGenerate(false)
  }

  const formatDate = (dateString: string) => {
    return format(new Date(dateString), 'dd MMMM yyyy', { locale: id })
  }

  if (loading) {
    return (
      <LayoutApp>
        <div className="flex items-center justify-center h-64">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
        </div>
      </LayoutApp>
    )
  }

  return (
    <LayoutApp>
      <div className="space-y-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold">Tahun Akademik</h1>
            <p className="text-muted-foreground">
              Kelola pengaturan tahun akademik dan semester otomatis
            </p>
          </div>
          <div className="flex gap-2">
            <Button
              onClick={() => setShowAutoGenerate(true)}
              className="flex items-center gap-2"
              variant="outline"
            >
              <Zap className="w-4 h-4" />
              Auto Generate
            </Button>
            <Button
              onClick={() => {
                setSelectedTahun(null)
                setShowDialog(true)
              }}
              className="flex items-center gap-2"
            >
              <Plus className="w-4 h-4" />
              Tambah Manual
            </Button>
          </div>
        </div>

        <Tabs defaultValue="overview" className="space-y-6">
          <TabsList>
            <TabsTrigger value="overview" className="flex items-center gap-2">
              <BarChart3 className="w-4 h-4" />
              Overview
            </TabsTrigger>
            <TabsTrigger value="manage" className="flex items-center gap-2">
              <Settings className="w-4 h-4" />
              Kelola Data
            </TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="space-y-6">
            {/* Tahun Akademik Selector */}
            <TahunAkademikSelector
              onTahunAkademikChange={setActiveTahunAkademik}
              showStats={true}
              allowChange={true}
            />

            {/* Quick Stats */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <Card>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                  <CardTitle className="text-sm font-medium">Total Tahun Akademik</CardTitle>
                  <Calendar className="h-4 w-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{tahunAkademik.length}</div>
                  <p className="text-xs text-muted-foreground">
                    {tahunAkademik.filter(ta => ta.isActive).length} aktif
                  </p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                  <CardTitle className="text-sm font-medium">Semester Saat Ini</CardTitle>
                  <BookOpen className="h-4 w-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">
                    {activeTahunAkademik ? getSemesterIcon(activeTahunAkademik.semester) : '📅'}
                  </div>
                  <p className="text-xs text-muted-foreground">
                    {activeTahunAkademik ? getSemesterLabel(activeTahunAkademik.semester) : 'Belum ada yang aktif'}
                  </p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                  <CardTitle className="text-sm font-medium">Data Tersimpan</CardTitle>
                  <CheckCircle className="h-4 w-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">
                    {activeTahunAkademik?._count ? 
                      (activeTahunAkademik._count.templateUjian + 
                       activeTahunAkademik._count.templateRaport + 
                       activeTahunAkademik._count.ujianSantri + 
                       activeTahunAkademik._count.raportSantri) : 0
                    }
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Total data tahun ini
                  </p>
                </CardContent>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="manage" className="space-y-6">
            <div className="grid gap-4">
              {tahunAkademik.map((tahun) => (
                <Card key={tahun.id} className={tahun.isActive ? 'ring-2 ring-primary' : ''}>
                  <CardHeader>
                    <div className="flex justify-between items-start">
                      <div>
                        <CardTitle className="flex items-center gap-2">
                          <span>{getSemesterIcon(tahun.semester)}</span>
                          {tahun.namaLengkap}
                          <Badge variant={tahun.isActive ? "default" : "secondary"}>
                            {tahun.isActive ? "Aktif" : "Nonaktif"}
                          </Badge>
                        </CardTitle>
                        <div className="flex items-center gap-4 mt-2 text-sm text-muted-foreground">
                          <div className="flex items-center gap-1">
                            <Calendar className="h-4 w-4" />
                            <span>{formatDateRange(tahun.tanggalMulai, tahun.tanggalSelesai)}</span>
                          </div>
                          {tahun.creator && (
                            <span>Dibuat oleh: {tahun.creator.namaLengkap}</span>
                          )}
                        </div>
                      </div>
                      <div className="flex gap-2">
                        {!tahun.isActive && (
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => handleSetActive(tahun.id)}
                            title="Aktifkan tahun akademik ini"
                          >
                            <CheckCircle className="h-4 w-4" />
                          </Button>
                        )}
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => {
                            setSelectedTahun(tahun)
                            setShowDialog(true)
                          }}
                          title="Edit tahun akademik"
                        >
                          <Edit className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => handleDelete(tahun.id)}
                          disabled={tahun.isActive}
                          title="Hapus tahun akademik"
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                  </CardHeader>
                  {tahun._count && (
                    <CardContent>
                      <div className="grid grid-cols-4 gap-4 text-sm">
                        <div className="text-center">
                          <p className="font-medium text-green-600">{tahun._count.templateUjian}</p>
                          <p className="text-muted-foreground">Template Ujian</p>
                        </div>
                        <div className="text-center">
                          <p className="font-medium text-blue-600">{tahun._count.templateRaport}</p>
                          <p className="text-muted-foreground">Template Raport</p>
                        </div>
                        <div className="text-center">
                          <p className="font-medium text-orange-600">{tahun._count.ujianSantri}</p>
                          <p className="text-muted-foreground">Ujian Santri</p>
                        </div>
                        <div className="text-center">
                          <p className="font-medium text-purple-600">{tahun._count.raportSantri}</p>
                          <p className="text-muted-foreground">Raport Santri</p>
                        </div>
                      </div>
                    </CardContent>
                  )}
                </Card>
              ))}

              {tahunAkademik.length === 0 && (
                <Card>
                  <CardContent className="text-center py-8">
                    <Calendar className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                    <p className="text-muted-foreground mb-4">
                      Belum ada tahun akademik. Gunakan Auto Generate untuk membuat tahun akademik otomatis.
                    </p>
                    <Button onClick={() => setShowAutoGenerate(true)}>
                      <Zap className="w-4 h-4 mr-2" />
                      Auto Generate Tahun Akademik
                    </Button>
                  </CardContent>
                </Card>
              )}
            </div>
          </TabsContent>
        </Tabs>

        {/* Dialogs */}
        <TahunAkademikDialog
          open={showDialog}
          onOpenChange={setShowDialog}
          tahunAkademik={selectedTahun}
          onSuccess={() => {
            fetchTahunAkademik()
            setSelectedTahun(null)
          }}
        />

        <AutoGenerateDialog
          open={showAutoGenerate}
          onOpenChange={setShowAutoGenerate}
          onSuccess={handleAutoGenerateSuccess}
        />
      </div>
    </LayoutApp>
  )
}