'use client'

import { useState } from 'react'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { useToast } from '@/hooks/use-toast'
import { Calendar, BookOpen, Users, FileText, CheckCircle, AlertCircle } from 'lucide-react'

interface PreviewItem {
  tahunMulai: number
  tahunSelesai: number
  semester: 'S1' | 'S2'
  namaLengkap: string
  tanggalMulai: string
  tanggalSelesai: string
  exists: boolean
  existingId?: number
  isCurrentActive: boolean
  willBeActive: boolean
  status: 'exists' | 'will_create'
}

interface AutoGenerateDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onSuccess: () => void
}

export function AutoGenerateDialog({ open, onOpenChange, onSuccess }: AutoGenerateDialogProps) {
  const [startYear, setStartYear] = useState(new Date().getFullYear())
  const [endYear, setEndYear] = useState(new Date().getFullYear() + 1)
  const [autoSetActive, setAutoSetActive] = useState(true)
  const [preview, setPreview] = useState<PreviewItem[]>([])
  const [isLoadingPreview, setIsLoadingPreview] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)
  const [showPreview, setShowPreview] = useState(false)
  const { toast } = useToast()

  const handlePreview = async () => {
    if (startYear > endYear) {
      toast({
        title: 'Error',
        description: 'Tahun mulai tidak boleh lebih besar dari tahun selesai',
        variant: 'destructive'
      })
      return
    }

    setIsLoadingPreview(true)
    try {
      const response = await fetch(`/api/admin/tahun-akademik/auto-generate?startYear=${startYear}&endYear=${endYear}`)
      const result = await response.json()

      if (result.success) {
        setPreview(result.data.preview)
        setShowPreview(true)
      } else {
        toast({
          title: 'Error',
          description: result.error || 'Gagal memuat preview',
          variant: 'destructive'
        })
      }
    } catch (error) {
      console.error('Preview error:', error)
      toast({
        title: 'Error',
        description: 'Terjadi kesalahan saat memuat preview',
        variant: 'destructive'
      })
    } finally {
      setIsLoadingPreview(false)
    }
  }

  const handleGenerate = async () => {
    setIsGenerating(true)
    try {
      const response = await fetch('/api/admin/tahun-akademik/auto-generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          startYear,
          endYear,
          autoSetActive
        })
      })

      const result = await response.json()

      if (result.success) {
        toast({
          title: 'Berhasil',
          description: result.message
        })
        onSuccess()
        onOpenChange(false)
        setShowPreview(false)
      } else {
        toast({
          title: 'Error',
          description: result.error || 'Gagal generate tahun akademik',
          variant: 'destructive'
        })
      }
    } catch (error) {
      console.error('Generate error:', error)
      toast({
        title: 'Error',
        description: 'Terjadi kesalahan saat generate tahun akademik',
        variant: 'destructive'
      })
    } finally {
      setIsGenerating(false)
    }
  }

  const getSemesterIcon = (semester: string) => {
    return semester === 'S1' ? '🌞' : '❄️'
  }

  const getStatusBadge = (item: PreviewItem) => {
    if (item.exists) {
      return (
        <Badge variant="secondary" className="flex items-center gap-1">
          <CheckCircle className="w-3 h-3" />
          Sudah Ada
        </Badge>
      )
    }
    return (
      <Badge variant="default" className="flex items-center gap-1">
        <AlertCircle className="w-3 h-3" />
        Akan Dibuat
      </Badge>
    )
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Calendar className="w-5 h-5" />
            Auto Generate Tahun Akademik
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6">
          {/* Form Input */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Pengaturan Generate</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="startYear">Tahun Mulai</Label>
                  <Input
                    id="startYear"
                    type="number"
                    value={startYear}
                    onChange={(e) => setStartYear(parseInt(e.target.value))}
                    min="2020"
                    max="2050"
                  />
                </div>
                <div>
                  <Label htmlFor="endYear">Tahun Selesai</Label>
                  <Input
                    id="endYear"
                    type="number"
                    value={endYear}
                    onChange={(e) => setEndYear(parseInt(e.target.value))}
                    min="2020"
                    max="2050"
                  />
                </div>
              </div>

              <div className="flex items-center space-x-2">
                <Switch
                  id="autoSetActive"
                  checked={autoSetActive}
                  onCheckedChange={setAutoSetActive}
                />
                <Label htmlFor="autoSetActive">
                  Otomatis set tahun akademik saat ini sebagai aktif
                </Label>
              </div>

              <div className="flex gap-2">
                <Button
                  onClick={handlePreview}
                  loading={isLoadingPreview}
                  variant="outline"
                  className="flex-1"
                >
                  <BookOpen className="w-4 h-4 mr-2" />
                  Preview
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Preview Results */}
          {showPreview && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Preview Tahun Akademik</CardTitle>
                <p className="text-sm text-muted-foreground">
                  Akan generate {preview.filter(p => !p.exists).length} tahun akademik baru
                </p>
              </CardHeader>
              <CardContent>
                <div className="space-y-3 max-h-60 overflow-y-auto">
                  {preview.map((item, index) => (
                    <div
                      key={index}
                      className={`flex items-center justify-between p-3 rounded-lg border ${
                        item.willBeActive ? 'border-blue-500 bg-blue-50' : 'border-gray-200'
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        <span className="text-lg">{getSemesterIcon(item.semester)}</span>
                        <div>
                          <p className="font-medium">{item.namaLengkap}</p>
                          <p className="text-sm text-muted-foreground">
                            {new Date(item.tanggalMulai).toLocaleDateString('id-ID')} - {' '}
                            {new Date(item.tanggalSelesai).toLocaleDateString('id-ID')}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        {item.willBeActive && (
                          <Badge variant="default" className="bg-blue-500">
                            Akan Aktif
                          </Badge>
                        )}
                        {item.isCurrentActive && (
                          <Badge variant="default" className="bg-green-500">
                            Aktif Saat Ini
                          </Badge>
                        )}
                        {getStatusBadge(item)}
                      </div>
                    </div>
                  ))}
                </div>

                <div className="flex gap-2 mt-4">
                  <Button
                    onClick={handleGenerate}
                    loading={isGenerating}
                    className="flex-1"
                    disabled={preview.filter(p => !p.exists).length === 0}
                  >
                    <FileText className="w-4 h-4 mr-2" />
                    Generate {preview.filter(p => !p.exists).length} Tahun Akademik
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() => setShowPreview(false)}
                  >
                    Batal
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Info Card */}
          <Card className="bg-blue-50 border-blue-200">
            <CardContent className="p-4">
              <div className="flex items-start gap-3">
                <AlertCircle className="w-5 h-5 text-blue-500 mt-0.5" />
                <div className="text-sm">
                  <p className="font-medium text-blue-900 mb-1">Sistem Tahun Akademik</p>
                  <ul className="text-blue-700 space-y-1">
                    <li>• <strong>Semester 1:</strong> Juli - Desember</li>
                    <li>• <strong>Semester 2:</strong> Januari - Juni</li>
                    <li>• Semua data akan otomatis tersimpan dengan tahun akademik yang sesuai</li>
                    <li>• Hanya satu tahun akademik yang bisa aktif dalam satu waktu</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </DialogContent>
    </Dialog>
  )
}