'use client'

import { useState } from 'react'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"
import { useToast } from "@/hooks/use-toast"
import { Calendar, Loader2 } from "lucide-react"
import { cn } from "@/lib/utils"

interface AutoGenerateResult {
  created: number
  skipped: number
  total: number
}

interface AutoGenerateDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onSuccess: () => void
}

export function AutoGenerateDialog({ open, onOpenChange, onSuccess }: AutoGenerateDialogProps) {
  const { toast } = useToast()
  const [loading, setLoading] = useState(false)
  const [startYear, setStartYear] = useState(String(new Date().getFullYear()))
  const [endYear, setEndYear] = useState(String(new Date().getFullYear() + 4))
  const [autoSetActive, setAutoSetActive] = useState(false)
  const [result, setResult] = useState<AutoGenerateResult | null>(null)

  const handleSubmit = async () => {
    const start = parseInt(startYear)
    const end = parseInt(endYear)

    if (isNaN(start) || isNaN(end)) {
      toast({
        title: "Error",
        description: "Tahun harus berupa angka yang valid",
        variant: "destructive"
      })
      return
    }

    if (start >= end) {
      toast({
        title: "Error",
        description: "Tahun akhir harus lebih besar dari tahun awal",
        variant: "destructive"
      })
      return
    }

    setLoading(true)
    setResult(null)

    try {
      const response = await fetch('/api/admin/tahun-akademik/auto-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          startYear: start,
          endYear: end,
          autoSetActive
        })
      })

      const data = await response.json()

      if (data.success) {
        setResult({
          created: data.data?.created ?? 0,
          skipped: data.data?.skipped ?? 0,
          total: data.data?.total ?? 0
        })
        toast({
          title: "Berhasil",
          description: data.message || `Berhasil membuat ${data.data?.created ?? 0} tahun akademik`
        })
        onSuccess()
      } else {
        throw new Error(data.message || 'Gagal membuat tahun akademik')
      }
    } catch (error: unknown) {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Gagal membuat tahun akademik",
        variant: "destructive"
      })
    } finally {
      setLoading(false)
    }
  }

  const handleClose = () => {
    if (!loading) {
      setResult(null)
      onOpenChange(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-[480px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Calendar className="h-5 w-5 text-primary" />
            Auto Generate Tahun Akademik
          </DialogTitle>
          <DialogDescription>
            Buat tahun akademik dan semester secara otomatis untuk beberapa tahun ke depan
          </DialogDescription>
        </DialogHeader>

        {result ? (
          <div className="py-6 space-y-4">
            <div className="text-center space-y-2">
              <div className="text-3xl font-bold text-primary">{result.created}</div>
              <p className="text-sm text-muted-foreground">Tahun akademik berhasil dibuat</p>
            </div>
            <div className="grid grid-cols-2 gap-4 text-center text-sm">
              <div className="bg-muted rounded-lg p-3">
                <div className="font-medium text-lg">{result.created}</div>
                <div className="text-muted-foreground">Dibuat</div>
              </div>
              <div className="bg-muted rounded-lg p-3">
                <div className="font-medium text-lg">{result.skipped}</div>
                <div className="text-muted-foreground">Diabaikan</div>
              </div>
            </div>
            <Button className="w-full" onClick={handleClose}>
              Selesai
            </Button>
          </div>
        ) : (
          <>
            <div className="grid gap-4 py-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="startYear">Tahun Awal</Label>
                  <Input
                    id="startYear"
                    type="number"
                    value={startYear}
                    onChange={(e) => setStartYear(e.target.value)}
                    placeholder="Contoh: 2024"
                    required
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="endYear">Tahun Akhir</Label>
                  <Input
                    id="endYear"
                    type="number"
                    value={endYear}
                    onChange={(e) => setEndYear(e.target.value)}
                    placeholder="Contoh: 2028"
                    required
                  />
                </div>
              </div>

              <div className="flex items-center space-x-2 pt-2">
                <Checkbox
                  id="autoSetActive"
                  checked={autoSetActive}
                  onCheckedChange={(checked) => setAutoSetActive(checked === true)}
                />
                <Label
                  htmlFor="autoSetActive"
                  className="text-sm font-normal leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer"
                >
                  Set tahun akademik terbaru sebagai aktif
                </Label>
              </div>

              <div className="bg-muted/50 rounded-lg p-3 text-sm text-muted-foreground">
                <p className="font-medium text-foreground mb-1">Yang akan dihasilkan:</p>
                <ul className="list-disc list-inside space-y-0.5">
                  <li>2 semester per tahun ({startYear}/{parseInt(startYear) + 1} - {endYear}/{parseInt(endYear) + 1})</li>
                  <li>S1 (Ganjil): Juli - Desember</li>
                  <li>S2 (Genap): Januari - Juni</li>
                </ul>
              </div>
            </div>

            <div className="flex justify-end gap-3">
              <Button variant="outline" onClick={handleClose} disabled={loading}>
                Batal
              </Button>
              <Button onClick={handleSubmit} disabled={loading}>
                {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                {loading ? 'Memproses...' : 'Generate'}
              </Button>
            </div>
          </>
        )}
      </DialogContent>
    </Dialog>
  )
}
